version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    # イメージ名の指定
    image: dashboard
    # コンテナ名の指定
    container_name: dashboard
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "cd app && yarn install && yarn start"
    ports:
      - "3000:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
